version: '2'

services:
  draft-content-api:
    build:
      context: .
    environment:
        APP_PORT: "8080"
        DRAFT_CONTENT_RW_ENDPOINT: "http://generic-rw-aurora:8080"
        API_YML: "./api.yml"
        MAPPER_YML: "./config.yml"
    ports:
        - 8080:8080
    depends_on:
        - upp-live-blog-post-validator
        - upp-live-blog-package-validator
        - upp-content-validator
        - upp-content-placeholder-validator
        - methode-article-mapper
        - generic-rw-aurora

  generic-rw-aurora:
    image: coco/generic-rw-aurora:v1.2.5
    environment:
      DB_CONNECTION_URL: "${GENERIC_RW_AURORA_DB_CONNECTION_URL}"
      DB_PERFORM_SCHEMA_MIGRATIONS: "false"
      APP_TIMEOUT: "10s"
      API_YML: "/config.yml"
    ports:
      - 8000:8080

  upp-live-blog-post-validator:
    image: coco/upp-live-blog-validator:v1.1.0-dev-bv-flags-rc3
    environment:
      APP_PORT: 8080
      ALLOWED_CONTENT_TYPES: "application/vnd.ft-upp-live-blog-post+json application/vnd.ft-upp-live-blog-post-internal+json"
      REMOVABLE_PROPERTIES: "alternativeTitles.promotionalTitleVariant _internal standout.breakingNews lastModified"
      JSON_SCHEMA_NAME: "live-blog-post.json"
      JSON_SCHEMAS_PATH: "/schemas"
      REMOVE_INTERNAL_CONTENT_TYPE: "true"
      CONTENT_TYPE_MAPPING: "application/vnd.ft-upp-live-blog-post+json=http://upp-content-validator.svc.ft.com/content/"
      BODY_VALIDATION_ENABLED: "false"
      QUEUE_ENABLED: "false"
    ports:
      - 8001:8080

  upp-live-blog-package-validator:
    image: coco/upp-live-blog-validator:v1.1.0-dev-bv-flags-rc3
    environment:
      APP_PORT: 8080
      ALLOWED_CONTENT_TYPES: "application/vnd.ft-upp-live-blog-package+json application/vnd.ft-upp-live-blog-package-internal+json"
      REMOVABLE_PROPERTIES: "alternativeTitles.promotionalTitleVariant _internal lastModified"
      JSON_SCHEMA_NAME: "live-blog-package.json"
      JSON_SCHEMAS_PATH: "/schemas"
      REMOVE_INTERNAL_CONTENT_TYPE: "true"
      CONTENT_TYPE_MAPPING: "application/vnd.ft-upp-live-blog-package+json=http://upp-content-validator.svc.ft.com/content/"
      BODY_VALIDATION_ENABLED: "false"
      QUEUE_ENABLED: "false"
    ports:
      - 8002:8080

  upp-content-validator:
    image: coco/upp-content-validator:v1.7.2
    environment:
      APP_NAME: "upp-article-validator"
      BODY_VALIDATION_ENABLED: "false"
      BODY_VALIDATOR_URL: "http://body-validation:8080"
      BODY_VALIDATOR_SERVICE_PATH: "/validate"
      BODY_VALIDATOR_GTG_PATH: "/__gtg"
      BODY_VALIDATION_TYPE_MAPPING: "application/vnd.ft-upp-article+json=application/vnd.ft-upp-html+xml application/vnd.ft-upp-article-internal+json=application/vnd.ft-upp-html-internal+xml"
      Q_PROCESSING_ENABLED: "false"
      Q_READ_ADDR: ""
      Q_READ_GROUP: uppArticleValidatorNativeCms
      Q_READ_TOPIC: NativeCmsPublicationEvents
      Q_WRITE_ADDR: ""
      Q_WRITE_TOPIC: CmsPublicationEvents
      CONTENT_URI_PREFIXES: "application/vnd.ft-upp-article+json=http://upp-content-validator.svc.ft.com/content/"
      SCHEMA_TYPES: "application/vnd.ft-upp-article+json"
      SCHEMA_TYPE_FOLDING: "true"
      SCHEMA_DELETED_TYPE: "application/vnd.ft-upp-deleted+json"
      INJECTOR_UNWRAPPING: "false"
      APP_PORT: 8080
      REMOVABLE_PROPERTIES: "alternativeTitles.promotionalTitleVariant, thisistest"
      BASE_SCHEMAS_URL: "http://localhost:8080"
    ports:
      - 8003:8080
    command: /upp-content-validator
    depends_on:
      - body-validation

  upp-content-placeholder-validator:
    image: coco/upp-content-validator:v1.7.2
    environment:
      APP_NAME: "content-placeholder-validator"
      BODY_VALIDATION_ENABLED: "false"
      BODY_VALIDATOR_URL: "http://body-validation:8080"
      BODY_VALIDATOR_SERVICE_PATH: "/validate"
      BODY_VALIDATOR_GTG_PATH: "/__gtg"
      BODY_VALIDATION_TYPE_MAPPING: "application/vnd.ft-upp-article+json=application/vnd.ft-upp-html+xml application/vnd.ft-upp-article-internal+json=application/vnd.ft-upp-html-internal+xml application/vnd.ft-upp-live-blog+json=application/vnd.ft-upp-html+xml application/vnd.ft-upp-live-blog-internal+json=application/vnd.ft-upp-html-internal+xml"
      Q_PROCESSING_ENABLED: "false"
      Q_READ_ADDR: ""
      Q_READ_GROUP: uppArticleValidatorNativeCms
      Q_READ_TOPIC: NativeCmsPublicationEvents
      Q_WRITE_ADDR: ""
      Q_WRITE_TOPIC: CmsPublicationEvents
      CONTENT_URI_PREFIXES: "application/vnd.ft-upp-content-placeholder+json=http://upp-content-validator.svc.ft.com/content/"
      SCHEMA_TYPES: "application/vnd.ft-upp-content-placeholder+json"
      SCHEMA_TYPE_FOLDING: "true"
      SCHEMA_DELETED_TYPE: ""
      INJECTOR_UNWRAPPING: "false"
      APP_PORT: 8080
      REMOVABLE_PROPERTIES: ""
    ports:
      - 8004:8080
    command: /upp-content-validator
    depends_on:
      - body-validation

  methode-article-mapper:
    image: coco/methode-article-mapper:1.28.5
    environment:
      KAFKA_ENABLED: "false"
      KAFKA_PROXY_URL: "localhost"
      DOCUMENT_STORE_API_ENABLED: "false"
      DOCUMENT_STORE_API_URL: "localhost"
      JAVA_OPTS: "-Xms256m -Xmx512m -XX:+UseG1GC -XX:+UseStringDeduplication -server"
      CONCORDANCE_API_ENABLED: "false"
      CONCORDANCE_API_URL: "localhost"
      NATIVE_TX_REF: "draftReference=draftReference"
      LAST_MODIFIED_SOURCE: "fromNative"
      TX_ID_SOURCE: "fromNative"
      TX_PROPERTY: "draftReference"
      API_HOST: "NA"
    ports:
      - 8005:8080

  body-validation:
    image: coco/body-validation-service:v0.3.1
    environment:
      JAVA_OPTS: "-Xms256m -Xmx512m -XX:+UseG1GC -XX:+UseStringDeduplication -server"
      BASE_SCHEMAS_URL: "http://localhost:8080/schemas"
    ports:
      - 9080:8080
      - 9081:8081      
