apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{.Values.service.name}}-admin-ingress
  annotations:
    # type of authentication
    ingress.kubernetes.io/auth-type: basic
    # name of the secret that contains the user/password definitions
    ingress.kubernetes.io/auth-secret: basic-auth
    # message to display with an appropiate context why the authentication is required
    ingress.kubernetes.io/auth-realm: "Authentication Required"
    ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
    - host: {{ template "cluster_subdomain" . }}.ft.com
      http:
        paths:
        - path: /__{{.Values.service.name}}/
          backend:
            serviceName: {{.Values.service.name}}
            servicePort: 8080
