apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{.Values.service.name}}-ingress
  annotations:
    # type of authentication
    ingress.kubernetes.io/auth-type: basic
    # name of the secret that contains the user/password definitions
    ingress.kubernetes.io/auth-secret: basic-auth
    # message to display with an appropiate context why the authentication is required
    ingress.kubernetes.io/auth-realm: "Authentication Required"
spec:
  rules:
{{ if eq .Values.target_env "preProdPac" }} 
  {{ if eq .Values.region "eu" }}
    - host: {{.Values.ingress.host_pre_prod_eu}}
  {{ else }}
    - host: {{.Values.ingress.host_pre_prod_us}}
  {{end}}
{{ end }}
      http:
        paths:
        - path: /drafts/content
          backend:
            serviceName: {{.Values.service.name}}
            servicePort: 8080
    - host: {{.Values.ingress.host}}
      http:
        paths:
        - path: /drafts/content
          backend:
            serviceName: {{.Values.service.name}}
            servicePort: 8080
